# Generated by Django 5.0.2 on 2024-05-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_biodata_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '1. Biodata'},
        ),
    ]
